# Generated by Django 5.1.1 on 2024-09-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='id',
            new_name='uuid',
        ),
    ]
